#!/usr/bin/env python3
"""
Regenerate apps/framework/data/technique_registry.yaml from TECHNIQUE_REGISTRY
after learning_tier / redundant_with have been computed.

Run from repo root: python3 scripts/sync_technique_registry_yaml.py

Import technique_playbooks first so apply_learning_tiers_to_registry() runs before
serialization — the YAML on disk must be correct at rest, not only after a side effect.
"""

from __future__ import annotations

import os
import sys
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps"))

# Allow bootstrap regen while on-disk YAML still has the Phase 14.5 regression.
os.environ["TAXONOMY_ASSERT_LEARNING_TIERS"] = "0"

# Side effect: mutates TECHNIQUE_REGISTRY in place with computed tiers.
import framework.technique_playbooks  # noqa: F401,E402
from framework.taxonomy import TECHNIQUE_REGISTRY, assert_learning_tier_distribution  # noqa: E402

OUT = ROOT / "apps" / "framework" / "data" / "technique_registry.yaml"

EXPECTED_TIER_COUNTS = Counter({4: 27, 3: 19, 2: 3, 1: 2})


def _entry_to_dict(entry) -> dict:
    raw = entry.to_dict()
    # Match on-disk YAML conventions (empty string, not null).
    if not raw.get("redundant_with"):
        raw["redundant_with"] = ""
    return raw


def main() -> None:
    assert_learning_tier_distribution(TECHNIQUE_REGISTRY)

    counts = Counter(t.learning_tier for t in TECHNIQUE_REGISTRY)
    if counts != EXPECTED_TIER_COUNTS:
        raise SystemExit(
            f"learning_tier distribution mismatch.\n"
            f"  expected: {dict(EXPECTED_TIER_COUNTS)}\n"
            f"  got:      {dict(counts)}"
        )

    payload = {"techniques": [_entry_to_dict(t) for t in TECHNIQUE_REGISTRY]}
    header = (
        "# Auto-generated by scripts/sync_technique_registry_yaml.py — do not hand-edit tier fields.\n"
        "# Regenerate after taxonomy or learning_tiers changes.\n"
    )
    OUT.write_text(
        header + yaml.dump(payload, sort_keys=False, default_flow_style=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({len(TECHNIQUE_REGISTRY)} techniques, tiers={dict(counts)})")


if __name__ == "__main__":
    main()
